name: oggm-simulator
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.8
  - jupyter
  - bokeh=2.4.0
  - nbserverproxy
  - tornado
  - ipywidgets
  - graphviz
  - numpy
  - scipy
  - pandas=1.3.3
  - shapely
  - netcdf4
  - configobj
  - xarray
  - pyviz_comms
  - param
  - holoviews=1.14.6
  - hvplot
  - panel=0.12.4
  - parambokeh
  - ipympl
  - pip:
    - joblib
    - progressbar2
    - git+https://github.com/OGGM/oggm.git
    - jupyter-panel-proxy
